# -*- coding: utf-8 -*-
"""Copy of yoloclass.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHWw2NgXNrqiHOQrgnX62AQs9GZEjSU-
"""

from google.colab import drive
drive.mount('/content/drive')
DATA_PATH = "/content/drive/MyDrive/project/cassava_split_dataset"

import os

print("Train folders:", sorted(os.listdir("/content/drive/MyDrive/project/cassava_split_dataset/train")))
print("Val folders:", sorted(os.listdir("/content/drive/MyDrive/project/cassava_split_dataset/val")))

!find /content/drive/MyDrive/project/cassava_split_dataset/train -type d

pip install ultralytics

import os
import shutil

def remove_cache_folders(path):
    for dir_name in os.listdir(path):
        full_path = os.path.join(path, dir_name)
        if os.path.isdir(full_path) and ('cache' in dir_name.lower() or dir_name.startswith('.')):
            print(f"Removing cache folder: {full_path}")
            shutil.rmtree(full_path)
remove_cache_folders('/content/drive/MyDrive/project/cassava_split_dataset/train')
remove_cache_folders('/content/drive/MyDrive/project/cassava_split_dataset/val')

print(os.listdir('/content/drive/MyDrive/project/cassava_split_dataset/train'))

from ultralytics import YOLO
model = YOLO('yolov8s-cls.pt')
model.train(data=DATA_PATH, epochs=20, imgsz=224)

from ultralytics import YOLO
model = YOLO("runs/classify/train/weights/best.pt")

print(model.names)

model.val()

import os
from glob import glob

val_dir = '/content/drive/MyDrive/project/cassava_split_dataset/val'
class_names = sorted(os.listdir(val_dir))
num_classes = len(class_names)

image_paths = []
true_labels = []

for idx, class_name in enumerate(class_names):
    class_dir = os.path.join(val_dir, class_name)
    for img_file in glob(os.path.join(class_dir, '*')):
        image_paths.append(img_file)
        true_labels.append(idx)

from ultralytics import YOLO
import numpy as np

model = YOLO("runs/classify/train/weights/best.pt")

pred_labels = []
probs = []

for img in image_paths:
    pred = model(img, imgsz=224, verbose=False)[0]
    pred_labels.append(pred.probs.top1)
    probs.append(pred.probs.data.tolist())

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

cm = confusion_matrix(true_labels, pred_labels)
disp = ConfusionMatrixDisplay(cm, display_labels=class_names)
disp.plot(cmap='Blues', xticks_rotation=45)
plt.title("Confusion Matrix")
plt.show()

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc

y_true_bin = label_binarize(true_labels, classes=list(range(num_classes)))
probs = np.array(probs)

plt.figure(figsize=(10, 8))
for i in range(num_classes):
    fpr, tpr, _ = roc_curve(y_true_bin[:, i], probs[:, i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f"{class_names[i]} (AUC = {roc_auc:.2f})")

plt.plot([0, 1], [0, 1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("Multi-class ROC Curve")
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('runs/classify/train/results.csv')

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(df['epoch'], df['train/loss'], label='Train Loss', color='blue')
plt.plot(df['epoch'], df['val/loss'], label='Validation Loss', color='orange')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.title('Training and Validation Loss')
plt.legend()
plt.grid(True)

plt.subplot(1, 2, 2)
plt.plot(df['epoch'], df['metrics/accuracy_top1'], label='Validation Accuracy (Top-1)', color='green')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.title('Validation Accuracy')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('runs/classify/train/results.csv')

epochs = df['epoch']
train_loss = df['train/loss']
val_loss = df['val/loss']
val_acc = df['metrics/accuracy_top1']

fig, ax1 = plt.subplots(figsize=(10, 6))

ax1.plot(epochs, train_loss, 'r-', label='Train Loss')
ax1.plot(epochs, val_loss, 'b-', label='Validation Loss')
ax1.set_xlabel('Epochs')
ax1.set_ylabel('Loss', color='black')
ax1.tick_params(axis='y')
ax1.legend(loc='upper left')

ax2 = ax1.twinx()
ax2.plot(epochs, val_acc, 'orange', label='Validation Accuracy')
ax2.set_ylabel('Accuracy', color='black')
ax2.tick_params(axis='y')
ax2.legend(loc='upper right')

plt.title('Training Loss & Accuracy')
plt.grid(True)
plt.tight_layout()
plt.show()

from ultralytics import YOLO
from PIL import Image
import torch

model = YOLO('/content/runs/classify/train/weights/best.pt')

image_path = "/content/drive/My Drive/Colab Notebooks/md?.jpg"

results = model(image_path)

predicted_index = results[0].probs.top1
predicted_class = results[0].names[predicted_index]

print(f"\n🧠 Predicted class: {predicted_class}")